version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: docker/golang/Dockerfile
    ports:
      - "8081:8080"
    command:
      "/bin/wordy"
  db:
    image: postgres:9.6
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:cached
    environment:
      POSTGRES_USER: wordy
      POSTGRES_DB: wordy
      POSTGRES_PASSWORD: 123456