// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"gorm.io/gorm"
	"wordy/src/controller"
	"wordy/src/postgre"
	"wordy/src/user"
)

// Injectors from wire.go:

// InitializeUserController for controller.CreateUserController
func InitializeUserController() (controller.User, error) {
	repository, err := InitializeUserRepository()
	if err != nil {
		return controller.User{}, err
	}
	user := controller.CreateUserController(repository)
	return user, nil
}

// InitializeUserRepository wire for postgre.NewUserRepository
func InitializeUserRepository() (user.Repository, error) {
	db, err := InitializeDBConnection()
	if err != nil {
		return nil, err
	}
	repository := postgre.NewUserRepository(db)
	return repository, nil
}

// InitializeDBConnection wire for postgre.NewDBConnection
func InitializeDBConnection() (*gorm.DB, error) {
	db, err := postgre.NewDBConnection()
	if err != nil {
		return nil, err
	}
	return db, nil
}
