// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"gorm.io/gorm"
	"wordy/src/controller"
	"wordy/src/postgre"
)

// Injectors from wire.go:

// InitializeUserController for controller.CreateUserController
func InitializeUserController() (controller.User, error) {
	userRepository, err := InitializeUserRepository()
	if err != nil {
		return controller.User{}, err
	}
	user := controller.CreateUserController(userRepository)
	return user, nil
}

// InitializeUserRepository wire for postgre.NewUserRepository
func InitializeUserRepository() (postgre.UserRepository, error) {
	db, err := InitializeDBConnection()
	if err != nil {
		return postgre.UserRepository{}, err
	}
	userRepository := postgre.NewUserRepository(db)
	return userRepository, nil
}

// InitializeDBConnection wire for postgre.NewDBConnection
func InitializeDBConnection() (*gorm.DB, error) {
	db, err := postgre.NewDBConnection()
	if err != nil {
		return nil, err
	}
	return db, nil
}
